sudo: false
addons:
  apt:
    packages:
      - build-essential
      - dvipng
      - ocaml
      - texlive-fonts-recommended
      - texlive-lang-greek
      - texlive-latex-recommended
language: node_js
node_js:
  - "4.3.0"
  - "4"
  - "5"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd ./tools/texvc && make
script: npm run-script coverage
after_success: npm run coveralls